name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Update gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 09d769135cb97a15f57c162ff8b27bdc
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: node dist/index.js
